# Generated by Django 3.2.6 on 2021-11-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='fName',
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
