# Generated by Django 3.2.6 on 2021-11-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_gender',
        ),
        migrations.AddField(
            model_name='customer',
            name='Occupation',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Job-Holder', 'Job-Holder')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile-white.png', null=True, upload_to=''),
        ),
    ]
