# Generated by Django 3.2.6 on 2021-11-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211123_0252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
