# Generated by Django 3.2.6 on 2022-01-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomment',
            name='blog',
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
