# Generated by Django 3.2.6 on 2022-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220107_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.CharField(blank=True, default='False', max_length=50, null=True),
        ),
    ]
