# Generated by Django 3.2.6 on 2022-01-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='review',
            field=models.TextField(blank=True, default='True', null=True),
        ),
    ]
