# Generated by Django 3.2.6 on 2022-01-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='review',
            field=models.CharField(blank=True, default='True', max_length=50, null=True),
        ),
    ]
