# Generated by Django 3.2.6 on 2022-01-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog'),
        ),
    ]
